### PR TITLE
Really all batteries

### LINKED ISSUE #146: Battery States are excluded
Hi Dwain,

I was wondering why the battery states are explicitly excluded from the battery page. I have a bunch of Homematic Devices, which only send a state as a binary sensor and prior changing your code and making a pull request I thought I should ask.

Thx

### LINKED ISSUE #157: [FR] Battery Status Page - Sort by level, ascending
* NOTE: If the battery status info page is *supposed* to sort by level, please let me know and I'll resubmit/change this to an 'issue'.

Area in question: House Data -> All Batteries.

Currently (at least on mine), this page lists the battery sensors in alphabetical order. I think it would make more sense to sort this page so that the entities with the lowest battery levels appear at the top of the page. (if possible).

It would also be a nice touch if we could define a certain level (ie: <5%, <10%, etc) after which the low-battery entities would get some sort of 'special treatment' - maybe a 'Dwains' notification to the main page, or some other 'front and center' indicator.

### PR DESCRIPTION
**Pull request by patman15**
Fixes #146 
Fixes #157 
I changed the way batteries are identified (domain + device_class) and added one card to be able to have correct sorting by battery state per domain (binary_sensor, sensor).

### CODE REVIEW

**Comment by dwainscheeren** [comment]
💯

**Comment by patman15** [comment]
Here is a preview example:
screenshot

**Comment by roblandry** [comment]
What are your thoughts about changing the sensor icon template to this:
```
                      [[[ 
                        var nok_states = ["Empty", "None", "unavailable", "unknown"];
                        if(states[`this.entity_id`]){
                          if (nok_states.includes(states[`this.entity_id`].state)){
                            return 'mdi:battery-alert';
                          } else if (states[`this.entity_id`].state != 'unknown' && states[`this.entity_id`].state <= 10) {
                            return 'mdi:battery-outline';
                          } else if (states[`this.entity_id`].state != 'unknown' && states[`this.entity_id`].state <= 95) {
                            var battery = Math.round(states[`this.entity_id`].state / 10) * 10
                            return 'mdi:battery-' + battery;
                          } else {
                            return 'mdi:battery';
                          }
                        }
                      ]]]
```
This grabs icons for other not ok states and displays the battery alert. This way, if it is ok, then itll be a full battery icon.

**Comment by patman15** [comment]
@roblandry since `state` is a string I'm not sure how standard the values are. Isn't that very integration specific? I couldn't find any "standard states" for batteries in the documentation of home assistant nor entity methods for e.g. "unavailable".
For further enhancements I would also first take a look at the [Battery State Card](https://github.com/maxwroc/battery-state-card) and whether this could be integrated as it is very powerful.

**Comment by roblandry** [comment]
@patman15 ,
I agree that state IS going to be integration specific, that is why i created a list, that can easily be updated. It works with the devices i have currently that need batteries replaced.
ZHA = unavailable or None
Fitbit = Empty

Otherwise these batteries showed as full which is counter intuitive. Additionally a config parameter could be created to encapsulate the users dead battery states in order to properly display. I could draft up a config if you think that is a better way.

**Comment by roblandry** [comment]
something as simple as this would catch all integrations (user defined):

adding a setting (i chose global config)
```
global:
  batteries: ['Empty', 'unknown', 'my_custom_dead_value']
```
and changing the list declaration to this:
```
                        var conf = {{ _d_t_config.global["batteries"] | tojson }};
                        var nok_states = (Array.isArray(conf) && conf.length) ? conf : 'unknown';
```

**Comment by roblandry** [comment]
Additionally, in order to provide color via gradient, this could be added.
```
                    styles:
                      icon:
                        - color: >
                            [[[
                              let conf = {{ _d_t_config.global["battery_empty_strings"] | tojson }};
                              let nok_states = (Array.isArray(conf) && conf.length) ? conf : 'unknown';
                              if (nok_states.includes(states[`this.entity_id`].state)) return '#ff0000';
                              else if (entity.state <= 0) return '#ff0000';
                              else if (entity.state <= 10) return '#ff5b00';
                              else if (entity.state <= 20) return '#ff8a00';
                              else if (entity.state <= 30) return '#ffb300';
                              else if (entity.state <= 40) return '#ffda00';
                              else if (entity.state <= 50) return '#ffff00';
                              else if (entity.state <= 60) return '#e3ff00';
                              else if (entity.state <= 70) return '#c3ff00';
                              else if (entity.state <= 80) return '#9eff00';
                              else if (entity.state <= 90) return '#6fff00';
                              else if (entity.state <= 100) return '#00ff00';
                              else return '#00ff00';
                            ]]]
```

**Comment by patman15** [comment]
> something as simple as this would catch all integrations (user defined):
> 
> adding a setting (i chose global config)
> 
> ```
> global:
>   battery_empty_strings: ['Empty', 'unknown', 'my_custom_dead_value']
> ```
> 
> and changing the list declaration to this:
> 
> ```
>                         let conf = {{ _d_t_config.global["battery_empty_strings"] | tojson }};
>                         let nok_states = (Array.isArray(conf) && conf.length) ? conf : 'unknown';
> ```
My humble opinion would be to go for this if absolutely necessary. I'm still not sure why your batteries are shown wrong. The [documentation](https://developers.home-assistant.io/docs/core/entity/sensor) clearly says that a `sensor` of `device_class battery` should return _% of battery that is left_. Since this is exactly what is queried in the current code, this sounds more like a issue with the ZHA/Fitbit integration which should be solved there. Can you post how your batteries are shown in the developer tools of home assistant?
As mentioned, just my humble opinion, it's **Dwains** theme, so his call how the rules are. :-)

**Comment by roblandry** [comment]
Well as for fitbit, Nest, and some other devices, they do not get % based on battery voltage, they get a Full/Medium/Empty, or something similar.

ZHA device trackers report None, as they are not in the house to report a battery level. Additionally when a sensor battery is dead, it reports unavailable if the server has been rebooted as it hasn't received an update because it is dead. Otherwise it would report a %.

I believe these devices are reporting correctly or within the confines of what the service provides.

Its fine though, i will just keep my edits to this as it provides what i believe is the best way forward. Additionally i think the page looks better with color values as apposed to the default color. Thanks for creating a PR to fix the batteries page. :+1:

**Pull request merged**
