### PR TITLE
Safety Devices

### PR DESCRIPTION
**Pull request by roblandry**
Added New Safety Section in header, rooms, and devices.

Use:
The sensor must return 'off', 'Ok', or 'Idle' when everything is fine, otherwise it will be marked as 'Unsafe'
If the sensor does not return either of these values, you must create a template sensor that does.
Additionally, you can create a issue with the values and we can look at adding it as a default.

Note:
Translations done via Google Translate. They may not all be correct. Assistance verifying would be awesome.

Closes: #130 
Documentation: #165

### CODE REVIEW

**Comment by roblandry** [comment]
I have found a way to pull in a list of devices vice a group and to get the ok/alert values, however this would be much different setup than the way all other config items are written. it would be this instead:
```
safety:
  - entity: sensor.entity_name
    ok: 'the ok value'
    alert: 'the alert value'
```
There would be lots of changes required to make this work. I am thinking it may not be worth it to make the necessary changes and not follow the them conventions to accomplish. These are a few snippits from 01-homepage.yaml

```
                              {% if room["safety"] %}
                                var v_safety = {{ room["safety"] | tojson }};
                                for (var i in v_safety) {
                                  var v_entity = ('entity' in v_safety[i]) ? v_safety[i]['entity'] : v_safety;
                                  var v_ok = ('ok' in v_safety[i]) ? v_safety[i]['ok'] : 'ok';
                                  var v_alert = ('alert' in v_safety[i]) ? v_safety[i]['alert'] : 'alert';
                                  //console.log(v_entity + v_ok + v_alert)
                                  if (states[v_entity].state != v_ok){
                                    additional_info += '<ha-icon style="height: 20px; color: var(--dwains-theme-accent)" icon="{{ _d_t_icons.safety_alert|default('mdi:shield-alert-outline') }}"></ha-icon><br>';
                                    break;
                                  }
                                }
                                //} else {
                                //  console.log("Dwains Theme Error: Invalid rooms.yaml:{{ room["name"] }}.safety entity!");
                                //  additional_info += 'S-E!<br>';
                                //}
                              {% endif %}
```

```
                      {% if devices.hasSafety == true %}
                      - type: custom:button-card
                        template: homepage_device
                        icon: "{{ _d_t_icons.safety_ok|default('mdi:shield-check') }}"
                        name: {{ _d_t_trans.safety.title_plural }}
                        tap_action: 
                          action: navigate
                          navigation_path: devices_safety#devices
                        label: >
                          [[[
                            var notOkSafety = 0;
                            {% for room in _d_t_config.rooms %}
                              {% if room["safety"] %}

                                var v_safety = {{ room["safety"] | tojson }};
                                for (var i in v_safety) {
                                  var v_entity = ('entity' in v_safety[i]) ? v_safety[i]['entity'] : v_safety;
                                  var v_ok = ('ok' in v_safety[i]) ? v_safety[i]['ok'] : 'ok';
                                  var v_alert = ('alert' in v_safety[i]) ? v_safety[i]['alert'] : 'alert';
                                  if (states[v_entity].state != v_ok){
                                    notOkSafety++;
                                  }
                                }

                              {% endif %}
                            {% endfor %}
                            if(notOkSafety > 0){
                              return notOkSafety + ' ' + hass.localize('component.binary_sensor.state.safety.on');
                            } else {  
                              return hass.localize('component.binary_sensor.state.safety.off');
                            }
                          ]]]
                      {% endif %}
```
I am thinking it may be best to just pick a few "default" values, that can be expounded upon if necessary. In the interim, a template sensor could be created to return the default values to make work.

Thoughts?

**Comment by ciechompl** [comment]
> Additionally, you can create a issue with the values and we can look at adding it as a default.

can I suggest to include also standard on / off states ? :)
on = alert !
off = all good / ok

**Comment by roblandry** [comment]
> > Additionally, you can create a issue with the values and we can look at adding it as a default.
> 
> can I suggest to include also standard on / off states ? :)
> on = alert !
> off = all good / ok

Consider it done! :+1:

**Comment by dwainscheeren** [comment]
Thanks! :) Going to work on this for 1.5

**Comment by roblandry** [comment]
@ciechompl ,
I rethought this, and added a global config option for user defined states. This way you can define your own states. Now no additional PRs will be required to match user integration strings.

in global:
```
global:
    safety_ok_strings: ["Ok", "Idle", "off"]
```
```

**Pull request merged**
