### PR TITLE
Page Entities: Add toggle for switch and light, and more info on hold.

### PR DESCRIPTION
**Pull request by roblandry**
Fixes page_entities  switch and light.

Used to display more info popup, now will toggle on/off and show more info on hold (long press).

### CODE REVIEW

**Comment by dwainscheeren** [comment]
Need to combine with #177

**Comment by roblandry** [comment]
So when 177 is merged, I will rebase.

**Comment by dwainscheeren** [comment]
I merged #177 please rebase if you got time

**Comment by dwainscheeren** [comment]
@roblandry

**Pull request merged**
