### PR TITLE
Vibration Sensor

### PR DESCRIPTION
**Pull request by roblandry**
Adds "vibration" config option to rooms.yaml
Adds vibration to the homepage header
Adds vibration to devices
Adds vibration to rooms

**Note: en translation is correct, all others are added to prevent breaking, but not translated.**
- [ ]  **Translation needed.**
- [ ]  **Documentation needed.**

### CODE REVIEW

**Comment by dwainscheeren** [comment]
Why not add vibration to safety devices?

**Comment by roblandry** [comment]
I suppose it depends on the use case. For instance, using it as a clothes washer / dryer monitor, would not be safety related. But using it as s sensor in a gun cabinet, would be. :man_shrugging:

**Comment by dwainscheeren** [comment]
That's true, but maybe people who use it for the dryer/washer can convert it into a device with state on/off?

**Comment by roblandry** [comment]
That's possible. I'm currently using device in place of any switches I have since there isn't a dedicated "switch" device. It doesn't work for my use case to consider switches as lights as my switches mostly power devices like tvs.
Personally I don't want to mix devices with switches (my tvs) and vibration sensors.

**Pull request merged**
